spring:
  profiles:
    active: mars-12302     
  application:
    name: eureka-rigister-server
 
eureka:
  instance:
    instance-id: server2:${server.port}
    perfer-ip-address: true
    ip-address: server2
  client:
    service-url:
      defaultZone: http://server1:12301/eureka/,http://server2:12302/eureka/
    register-with-eureka: false
    fetch-registry: true
  server:
    enable-self-preservation: true
